image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
for:
# configuration for "master" branch, build in Release mode
-
  branches:
    only:
      - master
  configuration: Release
# configuration for "development" branch, build in Dev mode
-
  branches:
    only:
      - development
  configuration: Dev
# "fall back" configuration for all other branches
# no "branches" section defined
configuration: Debug
before_build:
  - cmd: nuget install NUnit.Console -Version 3.7.0 -OutputDirectory tools
  - cmd: nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - cmd: nuget restore
  - cmd: choco install codecov
build:
  project: CDP4-SDK.sln
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
      - WebServicesDependent
after_test:
  - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\tools\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:".\CDP4Common.Tests\bin\Debug\net462\CDP4Common.Tests.dll .\CDP4JsonSerializer.Tests\bin\Debug\net462\CDP4JsonSerializer.Tests.dll " -filter:"+[CDP4Common*]* -[CDP4Common.Tests*]* +[CDP4JsonSerializer*]* -[CDP4JsonSerializer.Tests*]* " -output:"coverage.xml"
  - codecov -f "coverage.xml" -t b8924a0f-355e-4a9a-b304-f403231a6bcb
